# Generated by Django 3.2 on 2021-05-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicestatus',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='invoicestatus',
            name='icontext',
            field=models.CharField(default='icontext', max_length=128),
        ),
        migrations.AddField(
            model_name='invoicestatus',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
