# Generated by Django 3.2 on 2021-06-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='role',
            field=models.CharField(default='Consultant', max_length=128),
        ),
    ]
