# Generated by Django 3.2 on 2021-05-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210511_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_of_payment',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
