# Generated by Django 3.2 on 2021-07-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_wordtemplates'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordtemplates',
            name='code',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
