# Generated by Django 3.2 on 2021-06-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_crew_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crew',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['crew']},
        ),
        migrations.AddField(
            model_name='crew',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
