# Generated by Django 3.2 on 2021-05-26 11:36

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210525_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default='clients/default.jpg', upload_to=projects.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='place',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='plz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='street',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
