# Generated by Django 3.2 on 2021-05-30 15:42

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210526_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(default='clients/default.png', upload_to=projects.models.upload_to, verbose_name='Image'),
        ),
    ]
