# Generated by Django 3.2 on 2021-05-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='status',
            name='icontext',
            field=models.CharField(default='icontext', max_length=128),
        ),
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='status',
            name='subtext',
            field=models.CharField(default='text', max_length=128),
        ),
    ]
