# Generated by Django 3.2 on 2021-08-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_wordtemplates_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='short',
            field=models.CharField(default='A', max_length=5),
        ),
    ]
