# Generated by Django 3.2 on 2021-05-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210519_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_of_invoicing',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
