# Generated by Django 3.2 on 2021-08-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_client_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
