# Generated by Django 3.2 on 2021-08-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_is_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='part',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='place',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='plz',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='street',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
