# Generated by Django 3.2 on 2021-08-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210820_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
