# Generated by Django 3.2 on 2021-06-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210601_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='name',
            field=models.CharField(default='asd', max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='short',
            field=models.CharField(default='asd', max_length=4, unique=True),
        ),
    ]
