# Generated by Django 3.2 on 2021-08-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=4)),
                ('year', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
