# Generated by Django 3.2 on 2021-06-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210601_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominativ', models.CharField(max_length=3, unique=True)),
                ('genitiv', models.CharField(max_length=3, unique=True)),
                ('dativ', models.CharField(max_length=3, unique=True)),
                ('akkusativ', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='client',
            name='artikel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.artikel'),
        ),
    ]
