# Generated by Django 3.2 on 2021-06-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210608_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='akkusativ',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='dativ',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='genitiv',
            field=models.CharField(max_length=3),
        ),
    ]
