# Generated by Django 3.2 on 2021-06-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20210608_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='artikel',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
