# Generated by Django 3.2 on 2021-06-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210608_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='short',
        ),
    ]
