# Generated by Django 3.2 on 2021-06-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20210609_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='part',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
