# Generated by Django 3.2 on 2021-08-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='charges',
            name='amount_per_month',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
