# Generated by Django 3.2 on 2021-08-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_auto_20210825_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='item',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
