# Generated by Django 3.2 on 2021-08-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_alter_charges_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charges',
            name='item',
        ),
    ]
